import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { PerpetualGraph } from "../components/perpetualGraph";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Delimit</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/7/7d/Eo_circle_blue_letter-d.svg"
        />
      </Head>
      <div className={styles.title}>
        <div className={styles.cta}>
          <h1>Delimit</h1>
          <a href="https://app.de-limit.com/" target={"_blank"}>
            <div className={styles.fancyButton}>Enter App</div>
          </a>
          <h4>Defi limit orders for yield farming</h4>
        </div>
        <div className={styles.titleImage}>
          <PerpetualGraph/>
        </div>
      </div>
      <div className={styles.stats}>
        <div>
          <h3>$1.00</h3>
          <h5>DLMT Price</h5>
        </div>
        <div>
          <h3>$159M</h3>
          <h5>TVL</h5>
        </div>
        <div>
          <h3>2.3B</h3>
          <h5>Volume</h5>
        </div>
        <div>
          <h3>7,831</h3>
          <h5>Users</h5>
        </div>
      </div>
      {/* <div className={styles.features}>
        <div>
          <div className={styles.feature}>
            <h2>Limit Orders</h2>
            <p>
              <ul>
                <li>
                  Create multiple limit orders for deposited assets
                </li>
                <li>
                  Harvest and reinvest rewards from staked assets
                </li>
              </ul>
            </p>
          </div>
          <div className={styles.limitOrderImage}></div>
        </div>
        <div>
          <div className={styles.feature}>
            <h2>Universal Swap</h2>
            <ul>
              <li>
                Swap multiple ERC20/ERC721 tokens in a single transaction
              </li>
              <li>
                Swap liquidity pool and lending pool tokens
              </li>
            </ul>
          </div>
          <div className={styles.universalSwapImage}></div>
        </div>
      </div> */}
      {/* <div className={styles.integrations}>
        <h2>Integrations</h2>
        <div>
          <div>
            <img src="uniswap-uni-logo.svg" width="30px" />
            <h4>Uniswap</h4>
          </div>
          <div>
            <img src="sushiswap-sushi-logo.svg" width="30px" />
            <h4>Sushiswap</h4>
          </div>
          <div>
            <img src="aave-aave-logo.svg" width="30px" />
            <h4>AAVE</h4>
          </div>
          <div>
            <img src="pancakeswap-cake-logo.svg" width="30px" />
            <h4>Pancakeswap</h4>
          </div>
          <div>
            <img src="biswap-bsw-logo.svg" width="30px" />
            <h4>Biswap</h4>
          </div>
          <div>
            <img src="venus.png" width="30px" />
            <h4>Venus</h4>
          </div>
        </div>
      </div> */}
    </div>
  );
}
